### ISSUE TITLE
Issues when setup

### ISSUE THREAD

**Issue by carlitux** [Akin909/nvim-bufferline.lua#5] opened 2020-07-12 23:51 UTC
Getting this error when calling setup

```terminated by signal SIGSEGV (Address boundary error)```

When shows something like this 

![Screenshot from 2020-07-12 19-49-50](https://user-images.githubusercontent.com/40538/87259385-f2fce100-c478-11ea-8fd7-9ffaededdd0b.png)

and updates colorscheme

```
Error detected while processing ColorScheme Autocommands for "*":
Failed setting BufferLineSelectedIndicator highlight, something isn't configured correctly
Vim(highlight):E411: highlight group not found: BufferLineSelectedIndicator
Failed setting BufferLineModifiedSelected highlight, something isn't configured correctly
Vim(highlight):E411: highlight group not found: BufferLineModifiedSelected
Failed setting BufferLineModifiedInactive highlight, something isn't configured correctly
Vim(highlight):E411: highlight group not found: BufferLineModifiedInactive
````

**Comment by Akin909** [comment] 2020-07-13 06:08
@carlitux this is probably related to the theme you're using and whether or not it is setting certain highlight groups which the plugin uses to decide what colors to use. What theme are you using? does this happen if you try it with another theme?
Also just to be sure are you using nightly nvim, it won't work without that

**Comment by carlitux** [comment] 2020-07-13 19:59
Sorry for the vague context, I am just moving from dein to packer with all Lua code to config. In the process, I started getting the issue.

I use https://github.com/drewtempelmeyer/palenight.vim as a theme.

Maybe if you can guide me to debug the plugin I can have a better understanding of the issue and hopefully a PR.

**Comment by Akin909** [comment] 2020-07-13 20:57
@carlitux I've just tried that theme out locally and it works fine, can you tell me more about your setup. The plugin shouldn't really need any configuration after

 you load it with your package manager. Not sure how `dein` works at all but _after_ the plugin has been loaded you call `setup()`.

I made some changes this morning which might be why I don't see this error. Let me know if you try again and it's still erroring. If so can you try it with a minimal vimrc and see if it still errors e.g. only load the plugin and the theme.

![palenight](https://user-images.githubusercontent.com/22454918/87352943-d08bc600-c553-11ea-9bfe-98dccd53924f.png)

**Comment by carlitux** [comment] 2020-07-13 21:44
Sorry I didn't explain well.

Now I am using https://github.com/wbthomason/packer.nvim

```vim
set termguicolors
packadd packer.nvim
lua << EOF
local packer = require('packer')
local use = packer.use

packer.init()
use {'wbthomason/packer.nvim', opt = true}
use {'drewtempelmeyer/palenight.vim'}
use {'ryanoasis/vim-devicons', opt = true}
use { 
    'Akin909/nvim-bufferline.lua',
    requires = {'ryanoasis/vim-devicons', 'drewtempelmeyer/palenight.vim'},
    opt = true
}
EOF
```

manually

```vim
colorscheme palenight
packadd nvim-bufferline.lua
lua require'bufferline'.setup()
```

in this way I am able to reproduce the bug

**Comment by Akin909** [comment] 2020-07-13 22:24
Ah tbh I'm pretty unfamiliar with how the native packages work or how `packer` works. My guess would be the plugin is getting loaded at the wrong time somehow or before the highlights have been set I'm really not sure just a pure guess. When setup runs it expects the highlights it's using to be set.

In the minimal config you shared are you loading palenight somewhere? there is no packadd for the colorscheme :shrug:

**Comment by carlitux** [comment] 2020-07-13 22:32
yes, packer.nvim uses native packages.

As this is colorscheme using or not using packadd for palenight no difference.

**Comment by Akin909** [comment] 2020-07-13 22:38
If I get a chance I'll see if I can try and run it with native packages to reproduce or if you get the chance can you see if it works with something like `vim-plug` or `dein`

**Comment by carlitux** [comment] 2020-07-13 22:39
@Akin909 already it works with dein

**Comment by Akin909** [comment] 2020-07-14 07:32
Since this relates to another plugin/plugin manager I'm gonna close this let me know if you're still having issues

**Closed by Akin909** 2020-07-14 07:32 UTC
